export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const SET_INGREDIENTS = "SET_INGREDIENTS";
export const SET_INGREDIENTS_FAILED = "SET_INGREDIENTS_FAILED";

export const PURCHASE_BURGER_START = "PURCHASE_BURGER_START";
export const PURCHASE_BURGER_SUCCESS = "PURCHASE_BURGER_SUCCESS";
export const PURCHASE_BURGER_SUCCESS_FAILED = "PURCHASE_BURGER_SUCCESS_FAILED";
export const PURCHASE_BRUGER_INIT = "PURCHASE_BRUGER_INIT";

export const FETCH_ORDER_START= "FETCH_ORDER_START";
export const FETCH_ORDER_SUCCESS= "FETCH_ORDER_SUCCESS";
export const FETCH_ORDER_FAIL= "FETCH_ORDER_FAIL";

export const AUTH_START = "AUTH_START";
export const AUTH_START_SUCCESS = "AUTH_START_SUCCESS";
export const AUTH_START_FAIL = "AUTH_START_FAIL";

export const LOGOUT = "LOGOUT";

export const SET_AUTH_REDIRECT = "SET_AUTH_REDIRECT";